echo '<tr bgcolor="#074F91" class="tittle3"><td colspan="2" width="4" align="center">IMPLEMENTOS DE TRABAJO  </td><td colspan="1" width="4" align="center">SI</td><td colspan="1" width="4" align="center">NO</td></tr>';
echo '<tr bgcolor="#074F91" class="tittle3"><td colspan="2" width="4" align="center">CELULAR</td><td colspan="1" width="4" align="center">SI</td><td colspan="1" width="4" align="center">NO</td></tr>';
echo "<tr bgcolor='$color' class='text' id='implementos10'>";
echo "<td colspan='2'>Cuenta con celular con acceso a Internet?</td><td><input type='radio' name='implementos1'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos1'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos20'>";
echo "<td colspan='2'>La bateria de su Celular se encuentra Cargada?</td><td><input type='radio' name='implementos2'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos2'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos30'>";
echo "<td colspan='2'>Su celular cuenta con datos y minutos?</td><td><input type='radio' name='implementos3'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos3'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos40'>";
echo "<td colspan='2'>Tiene usted el cargador de su Celular?</td><td><input type='radio' name='implementos4'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos4'  class='obtener'  value='2'></td>";
echo "</tr>";
echo '<tr bgcolor="#074F91" class="tittle3"><td colspan="2" width="4" align="center">IMPRESORA</td><td colspan="1" width="4" align="center">SI</td><td colspan="1" width="4" align="center">NO</td></tr>';
echo "<tr bgcolor='$color' class='text' id='implementos50'>";
echo "<td colspan='2'>Cuenta con impresora suministrada por la Empresa?</td><td><input type='radio' name='implementos5'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos5'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='codigoimpresora'>";
echo "<td colspan='4'>Cual es el Codigo de su Impresora:<input  name='param20' id='param20' value='$rw2[8]' style='width:395px'; class='text' ></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos60'>";
echo "<td colspan='2'>La impresora se encuentra cargadal?</td><td><input type='radio' name='implementos6'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos6'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos70'>";
echo "<td colspan='2'>Cuenta con suficiente papel para la impresora?</td><td><input type='radio' name='implementos7'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos7'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos80'>";
echo "<td colspan='2'>Cuneta con el cargador de la Impresora?</td><td><input type='radio' name='implementos8'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos8'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos90'>";
echo "<td colspan='2'>Verifico que la Impresora este configurada con su celular?</td><td><input type='radio' name='implementos9'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos9'  class='obtener'  value='2'></td>";
echo "</tr>";
echo '<tr bgcolor="#074F91" class="tittle3"><td colspan="2" width="4" align="center">PESA</td><td colspan="1" width="4" align="center">SI</td><td colspan="1" width="4" align="center">NO</td></tr>';
echo "<tr bgcolor='$color' class='text' id='implementos100'>";
echo "<td colspan='2'>Cuenta con Pesa?</td><td><input type='radio' name='implementos10'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos10'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos110'>";
echo "<td colspan='2'>Su Pesa cuenta con Bateria?</td><td><input type='radio' name='implementos11'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos11'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos120'>";
echo "<td colspan='2'>Verifico que su Pesa cuente con bateria?</td><td><input type='radio' name='implementos12'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos12'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos130'>";
echo "<td colspan='2'>Verifico que su Pesa este funcionando Perfectamente?</td><td><input type='radio' name='implementos13'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos13'  class='obtener'  value='2'></td>";
echo "</tr>";

echo '<tr bgcolor="#074F91" class="tittle3"><td colspan="2" width="4" align="center">MALETA</td><td colspan="1" width="4" align="center">SI</td><td colspan="1" width="4" align="center">NO</td></tr>';
echo "<tr bgcolor='$color' class='text' id='implementos140'>";
echo "<td colspan='2'>Cuenta con Maleta?</td><td><input type='radio' name='implementos14'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos14'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='codigoimpresora'>";
echo "<td colspan='4'>Ultima vez que desinfecto la maleta:<input  name='param21' id='param21' value='$rw2[8]' style='width:395px'; class='text' ></td>";
echo "</tr>";
echo '<tr bgcolor="#074F91" class="tittle3"><td colspan="2" width="4" align="center">CARNET Y CARTA DE MOVILIDAD</td><td colspan="1" width="4" align="center">SI</td><td colspan="1" width="4" align="center">NO</td></tr>';
echo "<tr bgcolor='$color' class='text' id='implementos160'>";
echo "<td colspan='2'>Cuenta con Carnet?</td><td><input type='radio' name='implementos16'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos16'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos170'>";
echo "<td colspan='2'>Cuenta con carta de movilidad?</td><td><input type='radio' name='implementos17'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos17'  class='obtener'  value='2'></td>";
echo "</tr>";
echo '<tr bgcolor="#074F91" class="tittle3"><td colspan="2" width="4" align="center">PARAFISCALES O COPIA DE AFILIACION DE ARL</td><td colspan="1" width="4" align="center">SI</td><td colspan="1" width="4" align="center">NO</td></tr>';

echo "<tr bgcolor='$color' class='text' id='implementos180'>";
echo "<td colspan='2'>Tiene copia de pago de parafiscales?</td><td><input type='radio' name='implementos18'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos18'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos190'>";
echo "<td colspan='2'>Tiene copia de Afiliacion ARL(Peronal Nuevo)?</td><td><input type='radio' name='implementos19'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos19'  class='obtener'  value='2'></td>";
echo "</tr>";

<!-- echo "<tr bgcolor='$color' class='text' id='implementos200'>";
echo "<td colspan='2'>realizo cambio de tapabocas convencional lavable suministrado por la empresa y este se encuentra limpio?</td><td><input type='radio' name='implementos20'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos20'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos210'>";
echo "<td colspan='2'>realizo cambio de tapabocas convencional lavable suministrado por la empresa y este se encuentra limpio?</td><td><input type='radio' name='implementos21'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos21'  class='obtener'  value='2'></td>";
echo "</tr>";
echo "<tr bgcolor='$color' class='text' id='implementos220'>";
echo "<td colspan='2'>realizo cambio de tapabocas convencional lavable suministrado por la empresa y este se encuentra limpio?</td><td><input type='radio' name='implementos22'  class='obtener'   value='1' required></td><td><input type='radio' name='implementos22'  class='obtener'  value='2'></td>";
echo "</tr>"; -->
